### ISSUE TITLE
Brightness gain and other tests

### ISSUE THREAD

**Issue by qbancoffee** [shuuryou/imacg3#8]
I finally got around to testing the new additions and although functional there is an issue
and I noticed other older ones.
All this was testing on Ubuntu 20.04 on a raspberry pi 4

-Brightness gain works but it increases and decreases in the wrong direction.
it darkens to the right and brightens to the left.

-Pincushion button functions are reversed.

-Parallelogram button functions are reversed.

-pinbalance , s-correction and rotation use the same images but these are just cosmetic
and not important.

**Comment by shuuryou** [comment]
Not sure why logging in to GitHub closes an issue...

**Comment by shuuryou** [comment]
All of these are fixed, thanks for reporting.

Regarding the images: I stole them from the resource fork of the MacOS 9 screen settings. Since they only made images for user facing settings I didn't have any for the advanced settings. The rotation ones seemed to fit the most.

**Comment by qbancoffee** [comment]
No problem, happy to help!

I just tested but there is still an issue with the brightness gain. 
The slider position always starts at the left most position and when I  move it the screen goes blank. If I don't let go of the mouse button I can keep sliding right and the image reappears.

Also, I hadn't noticed this one before but when I try to use pin balance(both buttons) the image contorts and I can't fix it. Does this happen to you too?

**Comment by shuuryou** [comment]
I noticed that as well after commenting. It's fixed in commit 5255554 which I sneaked in after having said that it was fixed.

Pin balance also screws up my picture. I have no idea why. I'm treating it like all the other settings, just incrementing or decrementing. What happens on my CRT (made by LG; may be different for CPT CRTs):

* Picture is fine
* Click the pin balance adjustment buttons
* Nothing happens
* Click some more in one direction
* Bottom part of the picture skews to the right
* Click the other direction a few times
* Picture becomes normal again (if not, I click "Defaults" and spend the next 15 minutes redoing all the other adjustments)

Unfortunately I don't know if that is the intended behavior or how this control is supposed to be used. Maybe you're supposed to be making manual adjustments to the CRT electronics while using this? I just try not to touch it. But if there's a logic error in the control panel or sketch code, it should of course be fixed!

**Comment by qbancoffee** [comment]
Here is a video of pin balance should do and at least on my side when I click one of the buttons
it maxes out to a single value.

https://streamable.com/7cgfmg

I'll take a look at my sketch later on and see if there's an issue there.
